### ISSUE TITLE
Issue with Jamf-LAPS

### ISSUE THREAD

**Issue by hcstechgroup** [red5coder/Jamf-LAPS#1]
Thanks for making this app.  When I enter the serial number for a LAPS enabled Mac and the LAPS admin account, I get a message that says "Could not retrieve the password, please check the serial number and laps user name."  I can confirm via the jamf api that the serial and user name is correct and it will show me the current LAPS password.  Any thoughts as to why this does not work with your app?

**Comment by red5coder** [comment]
Hi there. Strange. It's currently working on my setup. Can we check a few things.

1. What version of Jamf Pro are you on?
2. I assume the fetch settings part works?
3. The Jamf Pro user name and admin account, do you know what permissions it has? Can you try with a full admin?

I'm just about to add some logging to the app. Let me doe that and then we can see if anything shows up there.

**Comment by red5coder** [comment]
I've seen the error. Just fixing and will post a new version shortly

**Comment by red5coder** [comment]
I've posted 0.9.1

Its has logging , to view you can use `sudo log stream --info --predicate 'subsystem=="uk.co.mallion.jamf-laps"'`

Also I think I found the issue, it was my bad. I was not passing the laps username to the API correctly. 

Let me know if this helps.

Thanks

**Comment by hcstechgroup** [comment]
Thanks for the prompt fix.  I am using JAMF Pro 10.46 with full admin rights.  All is working great now with the latest release.  I appreciate you taking the time to make this tool for the Mac community.  All the best.

**Comment by red5coder** [comment]
Excellent, thanks for the feedback.
